export enum RoleEnum {
  TECHNICAL_ADMIN = 'TECHNICAL_ADMIN',
  HELP_DESK = 'HELP_DESK',
  MANAGEMENT_ADMIN = 'MANAGEMENT_ADMIN',
  BLD = 'BLD',
  CRM = 'CRM',
  HRM = 'HRM',
  ACCOUNTANT = 'ACCOUNTANT',
  STUDENT = 'STUDENT',
  LECTURER = 'LECTURER'
}
