export const waitingCourseList = [
  { id: "id", title: "Id" },
  { id: "thumbnail", title: "Ảnh đại diện" },
  { id: "name", title: "Tên" },
  { id: "shortDescription", title: "Mô tả" },
  { id: "startDate", title: "Ngày bắt đầu giảng dạy" },
  { id: "endDate", title: "Ngày kết thúc giảng dạy" },
  { id: "createdBy", title: "Tạo bởi" },
  { id: "createAt", title: "Ngày tạo" },
  { id: "updateAt", title: "Ngày sửa" },
  { id: "originalPrice", title: "Giá gốc" },
  { id: "sellPrice", title: "Giá bán" },
  { id: "status", title: "Trạng thái" },
  { id: "createBy", title: "Tạo bởi" },
  { id: "updateBy", title: "Sửa bởi" },
  { id: "nameEn", title: "Tên tiếng anh" },
  { id: "duration", title: "Thời gian" },
  { id: "isApproved", title: "Trạng thái" },
  { id: "totalStudents", title: "Tổng học sinh" },
  { id: "totalReviews", title: "Tổng đánh giá" },
  { id: "averageRating", title: "Đánh giá trung bình" },
  { id: "category", title: "Danh mục" },
  { id: "lecturer", title: "Giảng viên" }
];
