export const MODAL_BODY_TYPES = {
  ADD: "ADD",
  EDIT: "EDIT",
  REMOVE: "REMOVE",
  DEFAULT: ""
};

export const CURRENT_PAGES = {
  CATEGORY_PAGE: "CATEGORY_PAGE",
  LECTURER_PAGE: "LECTURER_PAGE",
  EMPLOYEE_PAGE: "EMPLOYEE_PAGE",
  
};
