export const PERMISSIONS = {
  MANAGE_COURSE: 'MANAGE_COURSE',
  MANAGE_EMPLOYEE: 'MANAGE_EMPLOYEE',
  APPROVE_LECTURER_REGISTER: 'APPROVE_LECTURER_REGISTER',
  APPROVE_COURSE: 'APPROVE_COURSE',
  MANAGE_STUDENT: 'MANAGE_STUDENT',
  MANAGE_LECTURER: 'MANAGE_LECTURER'
};
