name: Eduhub BACKEND CI Pipeline

on:
  pull_request:
    branches:
      - backend/develop
      - backend/release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install dependencies
        run: |
          cd ./main 
          npm install

      - name: Run tests
        run: |
          cd ./main 
          npm run test

      - name: Test results
        if: failure()
        run: echo "Tests failed, cannot merge!"
